CREATE TABLE PERSONS 
(
  PERSON_ID NUMBER(15, 0) NOT NULL 
, FIRST_NAME VARCHAR2(30) 
, LAST_NAME VARCHAR2(30) 
, GENDER VARCHAR2(1) 
, CONSTRAINT PERSONS_PK PRIMARY KEY 
  (
    PERSON_ID 
  )
  ENABLE 
);

CREATE TABLE ADDRESSES 
(
  ADDRESS_ID NUMBER(10) NOT NULL 
, ADDRESS_LINE1 VARCHAR2(40) 
, ADDRESS_LINE2 VARCHAR2(240) 
, PERSON_ID NUMBER(15, 0) NOT NULL 
, CONSTRAINT ADDRESSES_PK PRIMARY KEY 
  (
    ADDRESS_ID 
  )
  ENABLE 
);

CREATE TABLE ORDERS 
(
  ORDER_ID NUMBER NOT NULL 
, ORDER_DATE DATE 
, ORDER_TOTAL NUMBER 
, PERSON_ID NUMBER 
, CONSTRAINT ORDERS_PK PRIMARY KEY 
  (
    ORDER_ID 
  )
  ENABLE 
);

CREATE VIEW PERSON_INFO
AS SELECT 
    PERSONS.GENDER GENDER, 
    PERSONS.LAST_NAME LAST_NAME, 
    PERSONS.FIRST_NAME FIRST_NAME, 
    ADDRESSES.ADDRESS_LINE2 ADDRESS_LINE2, 
    ADDRESSES.ADDRESS_LINE1 ADDRESS_LINE1, 
    ADDRESSES.ADDRESS_ID ADDRESS_ID, 
    ADDRESSES.ADDRESS_LINE1 ADDRESS_LINE1_1, 
    ADDRESSES.ADDRESS_LINE2 ADDRESS_LINE2_1, 
    ADDRESSES.ADDRESS_ID ADDRESS_ID1, 
    PERSONS.GENDER GENDER1, 
    PERSONS.LAST_NAME LAST_NAME1, 
    PERSONS.FIRST_NAME FIRST_NAME1 
FROM 
    ADDRESSES JOIN PERSONS USING (PERSON_ID);

ALTER TABLE ADDRESSES
ADD CONSTRAINT ADDRESSES_PERSONS_FK1 FOREIGN KEY
(
  PERSON_ID 
)
REFERENCES PERSONS
(
  PERSON_ID 
)
ENABLE;

ALTER TABLE ORDERS
ADD CONSTRAINT ORDERS_FK1 FOREIGN KEY
(
  PERSON_ID 
)
REFERENCES PERSONS
(
  PERSON_ID 
)
ENABLE;

CREATE SEQUENCE PERSONS_SEQ INCREMENT BY 1 START WITH 1;

CREATE TRIGGER PERSONS_TRG 
BEFORE INSERT ON PERSONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PERSON_ID IS NULL THEN
      SELECT PERSONS_SEQ.NEXTVAL INTO :NEW.PERSON_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
